thesisApp/autoiCV/autoapp/urls.py
from django.conf.urls import url
from django.urls import path
from autoapp import views

# TEMPLATE TAGGING
app_name = 'autoapp'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('base/', views.base, name='base'),
    path('training/', views.selected_model, name='training'),
    path('user_login/', views.user_login, name='user_login'),
    path('contact_upload/', views.contact_upload, name='contact_upload'),
    path('upload_csv/', views.upload_csv, name='upload_csv'),
    path('<str:room_name>/', views.room, name='room')

]

thesisApp/autoiCV/autoiCV/urls.py
from django.contrib import admin
from django.urls import path, include
from autoapp import views


urlpatterns = [
    path('', views.index, name='index'),
    path('autoapp/', include('autoapp.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

thesisApp/autoiCV/autoapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    # additional
    portofolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


class Info(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    ip_address = models.GenericIPAddressField(null=True)
    message = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

thesisApp/autoiCV/autoapp/forms.py
from django import forms
from django.contrib.auth.models import User
from autoapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portofolio_site', 'profile_pic')

thesisApp/autoiCV/autoapp/views.py
import csv, io
import logging
import pandas as pd

from django.shortcuts import render
from autoapp.models import Info
from django.http import JsonResponse
from autoapp.forms import UserForm, UserProfileInfoForm
from autoapp.process import extract_dataset_properties

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 79}
    return render(request, 'autoapp/index.html', context_dict)


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def other(request):
    return render(request, 'autoapp/upload_csv.html')


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'autoapp/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'autoapp/login.html', {})


def base(request):
    return render(request, 'autoapp/base.html', )


@permission_required('admin.can_add_log_entry')
def contact_upload(request):
    template = "autoapp/contact_upload.html"

    prompt = {
        'order': 'Order of CSV should be first_name, last_name, email, ip_address, message'
    }

    if request.method == 'GET':
        return render(request, template, prompt)

    csv_file = request.FILES['file']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'This is not a csv file')

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    # skip the header of the csv file
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        _, created = Info.objects.update_or_create(
            first_name=column[0],
            last_name=column[1],
            email=column[2],
            ip_address=column[3],
            message=column[4]
        )

    context = {}
    return render(request, template, context)


def upload_csv(request):
    data = {}
    properties = {}
    variables = {}
    rows = []

    if "GET" == request.method:
        return render(request, "autoapp/upload_csv.html", data)
    # if not GET, then proceed
    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'File is not CSV type')
            return HttpResponseRedirect(reverse("autoapp:upload_csv"))
        # if file is too large, return
        # if csv_file.multiple_chunks():
        #     messages.error(request, "Uploaded file is too big (%.2f MB)." % (csv_file.size / (10000 * 10000),))
        #     return HttpResponseRedirect(reverse("autoapp:upload_csv"))

        file_data = csv_file.read().decode("utf-8")
        io_string = io.StringIO(file_data)
        properties = extract_dataset_properties(io_string)

    except Exception as e:
        logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
        messages.error(request, "Unable to upload file. " + repr(e))



    #return HttpResponseRedirect(reverse("autoapp:upload_csv"))
    return render(request,"autoapp/upload_csv.html", properties)



def selected_model(request):
    try:
        results = request.GET['model_choice']

    except Exception as e:
        results = "Please select a model"
        # logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
        # messages.error(request, "Please select a model " + repr(e))

    return render(request,"autoapp/training.html", {'choice': results})


def room(request, room_name):
    return render(request, 'autoapp/chatroom.html', {
        'room_name': room_name
    })
    

thesisApp/autoiCV/templates/autoapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {# Custom JavaScript #}
    <script src="{% static 'js/main.js' %}" defer></script>

    {# jquery #}
<!--    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>-->

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap" rel="stylesheet">

    <title>base</title>
  </head>
  <body>
    <nav id="navbar-example2" class="navbar fixed-top navbar-dark bg-dark px-3">
      <a class="navbar-brand" href="{% url 'index' %}">AutoiCV4Rec</a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'autoapp:upload_csv' %}">Upload</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'autoapp:training' %}">Trainings</a>
        </li> -->


        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'autoapp:user_login' %}">Login</a>
          </li>
        {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Menu</a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'autoapp:other' %}">Dashboard</a></li>
          </ul>
        </li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
<!--      everything outside of this will be inherited if you extend!-->
      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  <!-- <nav class="navbar fixed-bottom navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand copright" href="#">Copyright@2021</a>
  </nav> -->
  </body>
</html>

thesisApp/autoiCV/templates/autoapp/chatroom.html
{% extends "autoapp/base.html"%}
{% load static %}
  {% block body_block %}
    <div>
    
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <form>
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatroom</label>
                            <textarea class="form-control" id="chat-text" rows="10"></textarea><br>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="input" type="text"></br>
                        </div>
                        <input class="btn btn-secondary btn-lg btn-block" id="submit" type="button" value="Send">
                    </form>
                </div>
            </div>
        </div>
    
        {{ request.user.username|json_script:"user_username" }}
        {{ room_name|json_script:"room-name" }}
        <script>
            const user_username = JSON.parse(document.getElementById('user_username').textContent);
            document.querySelector('#submit').onclick = function (e) {
                const messageInputDom = document.querySelector('#input');
                const message = messageInputDom.value;
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'username': user_username,
                }));
                messageInputDom.value = '';
            };
    
    
    
    
            const roomName = JSON.parse(document.getElementById('room-name').textContent);
    
            const chatSocket = new WebSocket(
                'ws://' +
                window.location.host +
                '/ws/chat/' +
                roomName +
                '/'
            );
    
            chatSocket.onmessage = function (e) {
                const data = JSON.parse(e.data);
                console.log(data)
                document.querySelector('#chat-text').value += (data.username + ': ' + data.message + '\n')
            }
        </script>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
        </script> -->
      </div>
{% endblock %}

thesisApp/autoiCV/templates/autoapp/index.html
<!doctype html>
{% extends "autoapp/base.html"%}
  {% block body_block %}
    <div class="welcome">
      <div class="baseline-container">
        <h5 class="baseline-title">Brief description of Session based recommendation systems</h5>
      </div>
      <p>Recommender systems (RS) are software applications that help users to find the item of interest based on their
      navigation behavior, usually with the aim of helping them in order to overcome information overload or make
      informed choices. This process is typically based on the assumption that long-term preference information about
      the individual users is available to the system</p>
    </div>
    <div>
      <a href="{% url 'autoapp:upload_csv' %}">Start the process--></a>
    </div>
    <div class="description">
      <div class="baseline">
        <div class="baseline-container">
          <h4 class="baseline-title">Baseline methods</h4>
        </div>
        
        <div class="row">
          <div class="col-sm">
            <div class="text-container">
              <div class="text-cont">
                <h5 class="text-title">Session-Based Popular Products (S-POP)</h5>
                  <p>This algorithm is based on session popularity predictor that gives higher scores to items with higher number of occurrences in the session. Ties are broken up by adding the popularity score of the item</p>
                  <p><b>It doesn’t care about any item features.</b>It just recommends popular items viewed by the user in the same session and popular items in general.</p>
              </div>
            </div>
            
          </div>
          <div class="col-sm">
            <div class="text-container">
              <div class="text-cont">
                <h5 class="text-title">Vector Multiplication Session-based K-Nearest Neighbors (VSKNN)</h5>
                <p>Session based KNN was implemented with some sampling techniques to ensure that its performance is not too slow. The algorithm has two parameters to tune (K and N) where K = 500 is the number of nearest neighbors and N = 1000 is the number of most recent candidate sessions. Then, the score of candidate items to be recommended from these sessions can be calculated using a distance metric like cosine similarity</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="neural">
         <div class="baseline-container">
          <h4 class="baseline-title">Neural Based methods</h4>
        </div>
         <div class="row">
           <div class="col-sm">
             <div class="bottom-cont">
               <div class="inner-cont">
                  <h5 class="text-title">Collaborative session-based recommendation machine (CSRM)</h5>
                  <p>A hybrid framework applying collaborative neighborhood information to the session-based recommendation was proposed by Wanget al.[66] who hypothesized that neigh-borhood sessions to the current session, even made by different users, can contain usefulinformation in improving the recommendation system predictions.</p>
                  <p><b>Main advantages</b></p>
                  <ul>
                    <li>1. Storing recent sessions and looking for neighborhoods within these sessions canbe beneficial, especially in e-commerce, where temporal drifts in user interestsoccur frequently.</li>
                    <li>2. Ease of including different item features in the representing item embedding vector,which can enhance the recommendations</li>
                  </ul>
               </div>
             </div>
             
           </div>
           <div class="col-sm">
            <div class="bottom-cont">
              <div class="inner-cont">
                <h5 class="text-title">Session-based recommendation with graph neural networks (SRGNN)</h5>
                <p>The paper introduces a new deep learning methodology for session based recommendation based on Graph neural networks (GNNs) called SR-GNN. The session sequences are modeled as a graph structured data and the GNNs are required to capture the complex transitions of items.</p>
                 <p>This architecture solves mainly two problems in other techniques. First, without adequate user behavior in a session, these methods won’t be able in estimating the user representations. Secondly, these methods always model single way transitions between items and neglect transitions among context</p>
              </div>
            </div>
             
           </div>
           <div class="col-sm">
            <div class="bottom-cont">
              <div class="inner-cont">
                <h5 class="text-title">Short-term attention/memory priority model (STAMP)</h5>
                <p>The paper introduces one of the session based recommendation systems based on sequence modeling using attention neural network. The main contribution in this paper is to introduce a solution to the long-term memory models (like GRU4Rec) that can be insufficient for modeling long sessions that contain user drift in his/her interests. The architecture is called STAMP as a short for short term attention priority model in which the attention weights are calculated from the session context and enhanced by current user interests to result in a compositional representation of the user temporal interests and more sensitive to the user interest drift (current interest represented by last click) occurring during the session itself</p>
                <p><b>Issues with the Architecture:</b> The architecture currently doesn’t support items with features. So, it is just the item-ID is the only feature that characterizes each item. This needs major changes in the architecture to be able to add more item features other than the identity feature
                 </p>
              </div>
            </div>
           </div>
         </div>
         <div class="baseline-container">
          <h4 class="baseline-title">Neural Based methods</h4>
        </div>
         <div class="row">
            <div class="col-sm">
              <div class="text-container">
                <div class="text-cont">
                  <h5 class="text-title">Neural attentive session-based recommendation (NARM)</h5>
                  <p>The basic idea of NARM is to build a hidden representation of the current session, and then generate predictions based on it. As shown in Figure 2, the encoder converts the input click sequence x = [x1, x2, ..., xt−1, xt ] into a set of high-dimensional hidden representations h = [h1, h2, ..., ht−1, ht ], which along with the attention signal at time t (denoted as αt ), are fed to the session feature generator to build a representation of the current session to decode at time t (denoted as ct ). Finally ct is transformed by a matrix U (as part of the decoder) into an activate function to produce a ranking list over all items, y = [y1,y2,...,ym−1,ym], that can occur in the current session</p>
                </div>
              </div>
            </div>
            <div class="col-sm">
              <div class="text-container">
                <div class="text-cont">
                  <h5 class="text-title">Simple generative convolutional network (NextItNet)</h5>
                  <p>The paper introduces a new deep learning model that integrates between the user history of preferences in addition to the present consumption motivations through an architecture called Behavioral Intensive Neural Network (BINN). This architecture is characterized by two parts, the weighted item2vec which is used in neural item embedding to get a unified item representation from the items attributes. In addition, the recurrent neural network which is used in discriminatory behavior learning</p>
                </div>
              </div>
            </div>
         </div>
      </div>

    </div>


  {% endblock %}

thesisApp/autoiCV/templates/autoapp/login.html
{% extends 'autoapp/base.html' %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>Please Login</h1>
        <form action="{% url 'autoapp:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">
        </form>
    </div>
</div>

{% endblock %}

thesisApp/autoiCV/templates/autoapp/upload_csv.html
{% extends "autoapp/base.html"%}
  {% block body_block %}
    <div class="row">
      <!-- left side of the menu -->
      <div class="col-sm">
        <div class="upload">
          <div class="content">
              <h4>Upload the dataset to start the processing</h4>
              <p>Make sure that your dataset contains sessionID and itemID</p>
              <form id="ulpload-form" action="{% url 'autoapp:upload_csv' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                  <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label"></label>
                  <div class="col-md-8">
                    <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
                  </div>
                </div>
                <div class="mybutton">
                    <div class="form-group">
                    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                         <button class="btn btn-primary"> <span class="fa fa-upload" aria-hidden="true"
                                                                style="margin-right:5px;"></span>Upload </button>
                    </div>
                </div>
                </div>
                <div class="error">
                    {% if messages %}
                      <ul class="messages">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                          {% endfor %}
                      </ul>
                    {% endif %}
                </div>
              </form>
            </div>
        </div>
      </div>

      <!-- right side of the menu -->
      <div class="col-sm">
        <div class="model-selection">
          <h4 class="model-title">Select the proposed model </h4>
          <p class="par">For hyper-parameters tuning</p>
          <div class="content-left">
            <form action="{% url 'autoapp:training' %}">
                <select id="select_model" name="model_choice" class="form-select" aria-label="Default select example">
                    <option disabled="true" selected>-- Select Model --</option>
                    <option>S-POP</option>
                    <option>VSKNN</option>
                    <option>CSRM</option>
                    <option>NextItNet</option>
                    <option>SRGNN</option>
                    <option>STAMP</option>
                    <option>NARM</option>
                </select>
                <div class="start-button">
                  <input id="submit" type="submit" value="Start" class="btn btn-primary">
                </div>
            </form>
          </div>

          <div class="predicted">
            <h5 class="pred">Predicted model: <b>{{model}}</b></h5>
            <!-- <h5 id="app" class="pred">Counter: {{text}}</h5> -->
          </div>

        </div>
      </div>
    </div>
    
    <div class="check">
      <h4 class="rowslabel">Dataset Properties </h4>
        <div class="row">
            <div class="col-sm">
                <h4 class="left-title">Training set</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Properties</th>
                        </tr>
                    </thead>
                      <tbody>
                        <tr>
                          <th scope="row">Number of items</th>
                          <td>{{items_tr}}</td>
                        </tr>
                        <tr>
                          <th scope="row">Number of clicks</th>
                          <td>{{clicks_tr}}</td>
                        </tr>
                        <tr>
                          <th scope="row">Number of sessions</th>
                          <td>{{sessions_tr}}</td>
                        </tr>
                        <tr>
                          <th scope="row">Average Session Length</th>
                          <td>{{average_session_length_tr}}</td>
                        </tr>
                        <tr>
                          <th scope="row">Average Item Frequency</th>
                          <td>{{average_freq_item_tr}}</td>
                        </tr>
                      </tbody>
                </table>
            </div>
            <div class="col-sm">
                <h4 class="left-title">Validation set</h4>
                <table class="table table-striped">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Properties</th>
                    </tr>
                </thead>
                  <tbody>
                    <tr>
                      <th scope="row">Number of items</th>
                      <td>{{items_ts}}</td>
                    </tr>
                    <tr>
                      <th scope="row">Number of clicks</th>
                      <td>{{clicks_ts}}</td>
                    </tr>
                    <tr>
                      <th scope="row">Number of sessions</th>
                      <td>{{sessions_ts}}</td>
                    </tr>
                    <tr>
                      <th scope="row">Average Session Length</th>
                      <td>{{average_session_length_ts}}</td>
                    </tr>
                    <tr>
                      <th scope="row">Average Item Frequency</th>
                      <td>{{average_freq_item_ts}}</td>
                    </tr>
                  </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
      document.querySelector('#submit').onclick = function (e) {
      const messageInputDom = document.querySelector('#input');
      const message = messageInputDom.value;
      chatSocket.send(JSON.stringify({
          'message': message,
          'username': user_username,
      }));
      messageInputDom.value = '';
  };
    </script>
  {% endblock %}